/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_chemist_highloadcup_jni_NativeNet */

#ifndef _Included_ru_chemist_highloadcup_jni_NativeNet
#define _Included_ru_chemist_highloadcup_jni_NativeNet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_test
  (JNIEnv *, jobject);

/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    bind
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_bind
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    unbind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_unbind
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    read
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_read
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    write
 * Signature: (JLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_write
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_init
  (JNIEnv *, jclass);

/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    epollCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_epollCreate
  (JNIEnv *, jclass);

/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    getEvents
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_getEvents
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    epollListen
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_epollListen
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ru_chemist_highloadcup_jni_NativeNet
 * Method:    eventsBuffer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_chemist_highloadcup_jni_NativeNet_eventsBuffer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
